### ISSUE TITLE
请问哪个参数是设置矿池手续费？

### ISSUE THREAD

**Issue by coolhty** [UlordChain/ulord-node-stratum-pool#15]
全局手续费和指定钱包的手续费，请问分别是哪两个参数？
改了手续费参数，是否能在不重启程序的情况下生效吗？

**Comment by ZyanWlayor** [comment]
coins/ulord.json 下的txfee字段是矿池地址抽成 单位%

**Comment by let5sne** [comment]
@ZyanWlayor 请问这个是百分比是怎么计算的呢，我看代码里面是减去一个固定值

`                       var feeSatoshi = coinsToSatoshies(fee);
                        var totalOwed = parseInt(0);
                        for (var i = 0; i < rounds.length; i++) {
                            // only pay generated blocks, not orphaned, kicked, immature
                            if (rounds[i].category == 'generate') {
                                totalOwed = totalOwed + coinsToSatoshies(rounds[i].reward) - feeSatoshi;
                            }
                        }`

**Comment by ZyanWlayor** [comment]
不好意思看错了，这个feeSatoshi是指矿池从每笔交易中扣除的固定抽成，这个在coins/ulord.json里配置，单位UT。
