### ISSUE TITLE
矿池服务开启，请问矿工如何访问矿池？

### ISSUE THREAD

**Issue by lynnnnnnnn** [UlordChain/ulord-node-stratum-pool#17]
地址和端口 分别在哪配置呢？

**Comment by ZyanWlayor** [comment]
配置位于pool_configs/ulord.json下的ports字段为端口配置，矿池地址为你的服务器地址。

**Comment by lynnnnnnnn** [comment]
好的

**Comment by lynnnnnnnn** [comment]
请问 ports 字段下的 tls 属性需要 设置为 true 吗
我设置为true 或者 为false 都没又开放端口 这是为什么呢？
