### ISSUE TITLE
Error sending payments, decreased rewards by too much!!

### ISSUE THREAD

**Issue by coolhty** [UlordChain/ulord-node-stratum-pool#18]
这是什么原因？
还有，在哪看矿工的余额呢？

**Comment by coolhty** [comment]
矿池不分币，然后看error里面有这个错误。。麻烦帮帮我。谢谢。

**Comment by coolhty** [comment]
可用余额有1000多个，结算的金额只有100个左右，还是不分币。
提示Error sending payments, decreased rewards by too much!!

**Comment by ZyanWlayor** [comment]
@coolhty 这个错误的原因是结算的时候发现账户余额不足，尝试着步进提高抽成额，但是超过了最高步进阈值，如果你更新了代码这个问题还存在，在社区@我。
