### ISSUE TITLE
npm update errors

### ISSUE THREAD

**Issue by myaleon** [UlordChain/ulord-node-stratum-pool#2]
I run "npm update" after I clone "ulord-node-stratum-pool", but seeing below errors:

======================

npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/bicliu/node-multi-hashing.git /root/.npm/_git-remotes/git-github-com-bicliu-node-multi-hashing-git-517b8fc4: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-bicliu-node-multi-hashing-git-517b8fc4'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/bicliu/node-multi-hashing.git /root/.npm/_git-remotes/git-github-com-bicliu-node-multi-hashing-git-517b8fc4: fatal: remote error:
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/bicliu/node-multi-hashing.git /root/.npm/_git-remotes/git-github-com-bicliu-node-multi-hashing-git-517b8fc4:   Repository not found.
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/root/.nvm/versions/node/v4.8.7/bin/node" "/root/.nvm/versions/node/v4.8.7/bin/npm" "update"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/bicliu/node-multi-hashing.git /root/.npm/_git-remotes/git-github-com-bicliu-node-multi-hashing-git-517b8fc4
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-bicliu-node-multi-hashing-git-517b8fc4'...
npm ERR! fatal: remote error:
npm ERR!   Repository not found.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/tmp/ulord-node-stratum-pool/npm-debug.log

======================

I run below commands to install nodejs:
 curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.10/install.sh | bash
 nvm install 4.8.7
 nvm use 4.8.7

This is node version
root@ubuntu-16:/var/tmp/ulord-node-stratum-pool# node -v
v4.8.7

Anything I was missing? Thanks guys.

**Comment by ZyanWlayor** [comment]
I am sorry.Due to internal project migration, there has been some bugs.
Please run follow command in at the root of the project:
`$rm -r node_modules`
`$npm update`
to rebuild dependencies.

**Comment by myaleon** [comment]
It works.

Thanks.

**Comment by taylorshuang** [comment]
Good！
