### ISSUE TITLE
About counterfeit shares

### ISSUE THREAD

**Issue by jxinhu** [UlordChain/ulord-node-stratum-pool#20]
There is a bug in other mining pools built with the node-stratum-pool code. There are false miners. The miner's hashrate is very high, but the corresponding proof-of-work  is not completed. We have noticed this problem and handed it, but we still need to be careful. If anyone encounters this problem or has any good suggestions，please leave a message here！

**Comment by ZyanWlayor** [comment]
oh，I'm interested in how you solved it.I'm trying to tightly control share's submission validation.I'm still watching

**Comment by jxinhu** [comment]
We just only recognized the problem and took steps to prevent it happening.
