### ISSUE TITLE
架设矿池后为什么占用CPU很高？

### ISSUE THREAD

**Issue by forest21000** [UlordChain/ulord-node-stratum-pool#21]
架设矿池后为什么占用CPU很高？需要做哪些优化吗？

**Comment by forest21000** [comment]
矿机连接的时候出现“connection reset by peer”的错误，一开始能连上，后来就出这个错了

**Comment by dyb1987** [comment]
forest21000 请问你配置文件如何修改的，方便加个好友么，一起研究下

**Comment by forest21000** [comment]
@dyb1987 我微信号forest21000
