### ISSUE TITLE
矿池这样显示，工作是否正常？如何提交官方

### ISSUE THREAD

**Issue by lovechina001** [UlordChain/ulord-node-stratum-pool#25]
![pool](https://user-images.githubusercontent.com/39551166/40411968-8bc5508a-5ea4-11e8-8020-96ca6e649db6.jpg)
![pool2](https://user-images.githubusercontent.com/39551166/40411971-8d66f376-5ea4-11e8-81de-b0fb8a0e9ef6.jpg)

矿池这样显示，工作是否正常？
要提交官方，如何 联系？
谢谢！

**Comment by ZyanWlayor** [comment]
这是正常的显示。
