### ISSUE TITLE
小白求助配置

### ISSUE THREAD

**Issue by dyb1987** [UlordChain/ulord-node-stratum-pool#26]
步骤0 
testnet=0
rpcuser=ulordpool
rpcpassword=ulordpool
txindex=1
addressindex=1
spentindex=1
timestampindex=1
reindex=1
这段配置应该在如何地方修改；

请问 pool_configs/ulord.json  配置文件中；

    "address": "UfhrEaZWrdJTKX5zpXFqAXTFbhAVG3bgb1",
    "_comment_address": "pools ulord address; ex, UjKNeYth9s1QkW1N6ubSorfKPA9JvkC39D",

    "validateWorkerUsername": true,

    "invalidAddress": "uhpm1PFGb56G3aZxF4feueab98kQcbLixk",
 
这些配置是什么意思，我应该如何修改；

**Comment by dyb1987** [comment]
方便留个联系方式，请假下么

**Comment by ZyanWlayor** [comment]
"address": "UfhrEaZWrdJTKX5zpXFqAXTFbhAVG3bgb1", //矿池地址
"validateWorkerUsername": true, //是否向守护进程验证矿机地址的有效性
"invalidAddress": "uhpm1PFGb56G3aZxF4feueab98kQcbLixk",//当支付时发现无效地址时用来替代的地址

**Comment by Bingordinary** [comment]
我想请教三个问题：
1，pool_configs/ulord.json文件的中
rpcuser=ulordpool
rpcpassword=ulordpool
请问下这是什么的账号密码？
2，pool_configs/ulord.json文件的中
      2.1 "rewardRecipients"参数也是写自己矿池的地址吗？
      2.2 “daemons”和"mposMode"中的"user"和"password"参数需要更改吗？这是什么

**Comment by Bingordinary** [comment]
@ZyanWlayor 求大佬指点

**Comment by Bingordinary** [comment]
0) Setting up coin daemon这个步骤中说的.ulordcore文件在哪里？我找不到
