### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:9889 这个错误怎么处理

### ISSUE THREAD

**Issue by jessezhang1986** [UlordChain/ulord-node-stratum-pool#28]
是不是哪里配置不对，或者那个进程没有启动？

0) Setting up coin daemon
Follow the build/install instructions for your coin daemon.Your ulord.conf file should end up looking something like this(you can find this file at a dir named .ulordcore):

这个文档没有看懂，没有找到名为“.ulordcore”的目录呀，是在哪里的呢？

**Comment by lynnnnnnnn** [comment]
你的 UlordChain 没有启动 守护进程
