### ISSUE TITLE
矿池服务器选型

### ISSUE THREAD

**Issue by forest21000** [UlordChain/ulord-node-stratum-pool#3]
我想搭建ulord矿池服务器，请问矿池的服务器配置应该是怎么样的？选择阿里云服务器可以吗？

**Comment by jackchen0120** [comment]
内核4G以上，阿里云服务器可以

**Comment by ZyanWlayor** [comment]
建议4核4G以上 io强化 阿里云可以

**Comment by taylorshuang** [comment]
The network bandwidth problem also needs to be considered.

**Comment by forest21000** [comment]
@jackchen0120 @ZyanWlayor @taylorshuang 谢谢回复，请问带宽多少合适呢？

**Comment by coolhty** [comment]
@jackchen0120  这个对网络要求高吗？用阿里云的话。

**Comment by tanlentboy** [comment]
矿池 需要配置 最低配置是什么条件？ 4核4G 200G存储 10M商用带宽 ？

**Comment by jackchen0120** [comment]
这个配置可以
