### ISSUE TITLE
启动没报错，但是不自动分币！！大神帮帮忙

### ISSUE THREAD

**Issue by coolhty** [UlordChain/ulord-node-stratum-pool#30]
可用余额不足的情况下报错：
Insufficient funds (225.93880846) to process payments (335.55829443); possibly waiting for txs.
嗯，这个我想得通，余额不够嘛，正常。

余额足够的情况下，报错：
Error sending payments, decreased rewards by too much!!!

找到源码报错的地方：
if (result.error && result.error.code === -6) {
                        // check if it is because we don't have enough funds
                        if (result.error.message && result.error.message.includes("insufficient funds")) {
                            command = []
                            logger.warning(logSystem, logComponent, JSON.stringify(payTrack));
                            logger.error(logSystem, logComponent, "Error sending payments, decreased rewards by too much!!!");
                        } else {
                            logger.warning(logSystem, logComponent, payTrack);
                            logger.error(logSystem, logComponent, 'Error sending payments ' + JSON.stringify(result.error));
                        }
                        command = [];
                    }

result.error.message && result.error.message.includes("insufficient funds")
如果错误消息包含insufficient funds就报这个错，翻译过来也是余额不足。

意思就是，不管余额足不足，反正就是不足。。横竖都是不足。

**Comment by ZyanWlayor** [comment]
不好意思 这是代码问题导致的，请更新最新的代码，并且提高抽成
