### ISSUE TITLE
‘最近挖到的区块’在页面上过一段时间会消失

### ISSUE THREAD

**Issue by fabius8** [UlordChain/ulord-node-stratum-pool#40]
root@iZuf632fhj1zoqmvdfso7mZ:/data/github/ulord-node-stratum-pool# redis-cli
127.0.0.1:6379> KEYS *
 1) "ulord:blocksConfirmed"
 2) "ulord:stats"
 3) "ulord:immature"
 4) "0"
 5) "ulord:balances"
 6) "ulord:shares:roundCurrent"
 7) "statHistory"
 8) "ulord:payments"
 9) "coinVersionBytes"
10) "ulord:shares:timesCurrent"
11) "ulord:hashrate"
12) "1"
13) "ulord:payouts"

**Comment by ZyanWlayor** [comment]
你好，最近挖到的区块是指那些已经出块但是未确认的块。当块被确认且支付之后，前端将不会显示。

**Comment by ZyanWlayor** [comment]
目前代码已更新为显示当天挖到的所有区块。
