### ISSUE TITLE
启动出现错误，求助

### ISSUE THREAD

**Issue by Bingordinary** [UlordChain/ulord-node-stratum-pool#41]
bash错误信息：
> ulord-pool@0.1.0 start /root/ulord-node-stratum-pool
> node init.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/ulord-node-stratum-pool/init.js:6:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Linux 2.6.32-042stab128.2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! ulord-pool@0.1.0 start: `node init.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ulord-pool@0.1.0 start script 'node init.js'.
npm ERR! This is most likely a problem with the ulord-pool package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node init.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ulord-pool
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ulord-pool
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/ulord-node-stratum-pool/npm-debug.log

===================================分隔线========================================
npm-debug.log记录内容：

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.11
3 info using node@v4.8.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart ulord-pool@0.1.0
6 info start ulord-pool@0.1.0
7 verbose unsafe-perm in lifecycle true
8 info ulord-pool@0.1.0 Failed to exec start script
9 verbose stack Error: ulord-pool@0.1.0 start: `node init.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:862:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid ulord-pool@0.1.0
11 verbose cwd /root/ulord-node-stratum-pool
12 error Linux 2.6.32-042stab128.2
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.8.7
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error ulord-pool@0.1.0 start: `node init.js`
17 error Exit status 1
18 error Failed at the ulord-pool@0.1.0 start script 'node init.js'.
18 error This is most likely a problem with the ulord-pool package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node init.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs ulord-pool
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls ulord-pool
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by taylorshuang** [comment]
需要把你nodejs的版本贴出来

**Comment by ZyanWlayor** [comment]
这可能因为你没有安装项目依赖导致的，你的nodejs和npm版本是正确的，确认有执行过`npm update`这一步。
