### ISSUE TITLE
请问debug.log文件中的日志，显示Masternodes: 0, peers who asked us for Masternode list: 3，是否正常？

### ISSUE THREAD

**Issue by maldiohead** [UlordChain/ulord-node-stratum-pool#42]
![default](https://user-images.githubusercontent.com/23315692/40581329-206303fa-6188-11e8-8396-b86c227cdaab.png)
如图

**Comment by taylorshuang** [comment]
这个主题关于矿池，关于全节点编译问题，请移步ulordchain，谢谢。
