### ISSUE TITLE
pool集群

### ISSUE THREAD

**Issue by suxiaochun** [UlordChain/ulord-node-stratum-pool#43]
现在是一台 如何搭建两台或多台的集群呢，请帮忙给说下

**Comment by taylorshuang** [comment]
可以把ulord守护进程放一台，web放一台，矿池程序一台，redis一台，web程序通过redis访问显示状态。更细粒度的分割需要代码重构了。

**Comment by lynnnnnnnn** [comment]
@taylorshuang 如何把web放在另一台服务器，如何配置呢？

**Comment by jackchen0120** [comment]
@lynnnnnnnn init.js 文件注释掉挖矿服务和支付功能函数调用spawnPoolWorkers();

    startPaymentProcessor();

**Comment by jackchen0120** [comment]
@lynnnnnnnn init.js 文件注释掉挖矿服务和支付功能函数调用spawnPoolWorkers();

startPaymentProcessor();

**Comment by jackchen0120** [comment]
@lynnnnnnnn 打开init.js 文件注释调用挖矿服务函数和支付功能函数，如： spawnPoolWorkers();   startPaymentProcessor();

**Comment by jackchen0120** [comment]
@lynnnnnnnn 复制一份矿池代码到web服务器，打开init.js 文件注释调用挖矿服务函数和支付功能函数，如： spawnPoolWorkers(); startPaymentProcessor();
