### ISSUE TITLE
getblocktemplate call failed for daemon instance 0 with error {"code":-9,"message":"Ulord Core is not connected!"}

### ISSUE THREAD

**Issue by daoying007** [UlordChain/ulord-node-stratum-pool#44]
运行环境，docker里，ubuntu16.04
启动的时候偶尔会报这个错误

kill掉 npm进程，重新 npm start就没有问题了。过程中没有重启 ulordd，所有ulordd应该是没有问题的。
<img width="959" alt="1" src="https://user-images.githubusercontent.com/39725475/40646245-33225322-635b-11e8-9639-b953be36df56.png">

**Comment by bicliu** [comment]
如果你可以直接在ulordd，运行rpc命令./ulord-cli getinfo,查看有多少个网络连接（字段"connections":）；
你这个问题出现们应该是没有一个可用的网络连接导致出现的，建议你检查一下ulordd的网络环境是否稳定，可靠。

**Comment by bicliu** [comment]
如果你可以直接运行rpc命令./ulord-cli getinfo,你可以查看有多少个网络连接（字段"connections":）；错误码提示，出问题的时候，连接数为0；
你这个问题出现们应该是没有一个可用的网络连接导致出现的，建议你检查一下ulordd的网络环境是否稳定，可靠。

**Comment by ZyanWlayor** [comment]
从代码上来看，是因为从不稳定的节点获取当前高度失败导致矿池认为区块已经同步完成，重启矿池即可。

**Comment by daoying001** [comment]
@bicliu 
<img width="1144" alt="1" src="https://user-images.githubusercontent.com/39725475/40695666-c6fa61cc-63f4-11e8-89ab-589a6ce41b90.png">

**Comment by daoying001** [comment]
@ZyanWlayor  重启确实是好了的，这种情况偶尔发生的，最好系统能够自动识别，自动恢复（自动重启）
