### ISSUE TITLE
升级程序有什么方法热部署吗？

### ISSUE THREAD

**Issue by coolhty** [UlordChain/ulord-node-stratum-pool#49]
杀死进程再启动进程有时候矿机会出问题。

**Comment by jackchen0120** [comment]
是出现什么问题，能提供截图吗

**Comment by coolhty** [comment]
@jackchen0120   也不是百分百。。就是杀死进程然后再运行，矿机可能会掉线后无法连接进来，要通知矿工重启矿机才行。如果可以不用重启程序升级程序就好了。

**Comment by jackchen0120** [comment]
可以考虑
