### ISSUE TITLE
转账时间固定为每天零点零分是么？

### ISSUE THREAD

**Issue by let5sne** [UlordChain/ulord-node-stratum-pool#7]
https://github.com/UlordChain/ulord-node-stratum-pool/blob/689e1feef9574bf9460b77e790dbad71033d7001/libs/paymentProcessor.js#L145
翻了下代码看到转账是通过定时函数，每天零点零分执行，是这样的么？可否改为可配置的呢？

**Comment by ZyanWlayor** [comment]
支付时间为服务器0点，可以用date命令查看服务时间。

**Comment by let5sne** [comment]
@ZyanWlayor 好的，刚测试了确实如此。
